[package]
name = "rust-adventure"
version = "0.1.0"
authors = ["Arnaud Tournier <arnaud.tournier@stack-labs.com>"]
edition = "2018"

[dependencies]
rand = "0.4.0"

[[bin]]
name = "rust-adventure"
path = "main.rs"

